### ISSUE TITLE
B+->B0 K+ is an annoying decay descriptor

### ISSUE THREAD

**Issue by po10** [po10/BAE#6]
The dimuon candidate is B0->mumu with no CC. This means when we try to CC the mumuK combination we get no candidates for one case. 

We could fix this via FilterInTrees or SubPID.

 | "# B+ -> B0  K+ "                               |       519 |        391 |    0.75337 |    0.91491 |      0.0000 |      7.0000 |
 | "# B- -> B~0  K- "                              |       519 |          0 |     0.0000 |     0.0000 |      0.0000 |      0.0000 |

**Comment by petitcactusorange** [comment]
Agreed. Maybe we should do a SubPID and call B0 a J/psi ?

**Comment by po10** [comment]
OK I can try this. I have never changed a composite particle with SubPID before but I assume it will work.

**Comment by po10** [comment]
For the upcoming stripping it would be good to change the descriptor to J/psi -> mumu, although I guess this will be done be default by looking directly at B->J/psi K X
